prod:
  push:
    - docker:
        image: node:20
        # volumes缓存：https://docs.cnb.cool/zh/grammar/pipeline.html#volumes
        volumes:
          - /root/.npm:cow

      # 加载密钥到环境变量：https://docs.cnb.cool/zh/env.html#dao-ru-huan-jing-bian-liang
      imports:
        - https://cnb.cool/my-cnb/KeyConfig/-/blob/main/.sls-ali.yml

      stages:
        - name: 编译
          script: npm install && npm run build
        - name: 查看目录
          script:
            - ls -a
            - ls -a dist

          # https://docs.cnb.cool/zh/plugins/public/tencentcom/scp
        - name: 使用 scp 将文件上传到服务器
          image: tencentcom/scp
          settings:
            host: $REMOTE_HOST
            username: $REMOTE_USERNAME
            key: $PRIVATE_KEY
            port: $REMOTE_PORT
            target: /tmp
            source: ./dist

          # https://docs.cnb.cool/zh/plugins/public/tencentcom/ssh
        - name: 通过 ssh 执行命令
          image: tencentcom/ssh
          settings:
            host:
              - ${REMOTE_HOST}
            username: ${REMOTE_USERNAME}
            key: ${PRIVATE_KEY}
            port: ${REMOTE_PORT}
            command_timeout: 2m
            script: |
              cd /tmp/dist
              ls -al
              mv /tmp/dist/* /opt/1panel/apps/openresty/1p-openresty/www/sites/blog.miyou.top/index
              rm -rf /tmp/dist
